default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PGHOST') { 'db' } %>
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# test:
#   <<: *base
#   database: <%= ENV['MYSQL_DATABASE'] || 'fae_dummy_test' %>
#   username: <%= ENV['MYSQL_USER'] || 'root' %>
#   password: <%= ENV['MYSQL_PASSWORD'] %>
#   host: <%= ENV['DEV_MYSQL_HOST'] || 'localhost' %>

  # =======================================

# development:
#   <<: *default
#   database: fae_engine

# test:
#   <<: *default
#   database: fae_deploy_test_test

production:
  url: <%= ENV['DATABASE_URL'] %>
